[build]
  base = "."
  publish = "dist"
  command = "rm -rf node_modules package-lock.json yarn.lock && npm install --no-audit --no-fund && npm run build"

[build.environment]
  # Ensure Node version aligns with local if needed; falls back to site setting
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"


