[build]
  base = "."
  publish = "dist"
  command = "rm -rf node_modules package-lock.json yarn.lock && npm install --omit=optional --no-audit --no-fund --ignore-scripts && npm run build"

[build.environment]
  # Ensure Node version aligns with local if needed; falls back to site setting
  NODE_VERSION = "20"
  NPM_FLAGS = "--omit=optional --no-audit --no-fund --ignore-scripts"
  NPM_CONFIG_OPTIONAL = "false"


