
    import React from 'react';
    export const cryptoPaymentOptions = [
      { name: 'Bitcoin (BTC)', symbol: 'BTC', address: 'bc1q...', network: 'Bitcoin' },
      { name: 'Ethereum (ETH)', symbol: 'ETH', address: '0xABCD...', network: 'ERC20' },
      { name: 'Solana (SOL)', symbol: 'SOL', address: 'SoL1...', network: 'Solana' },
      { name: 'USDT (ERC20)', symbol: 'USDT', address: '0xEFGH...', network: 'ERC20' },
      { name: 'USDC (ERC20)', symbol: 'USDC', address: '0xIJKL...', network: 'ERC20' },
      { name: 'Binance Coin (BNB)', symbol: 'BNB', address: 'bnb1...', network: 'BEP20 (BSC)' },
      { name: 'Cardano (ADA)', symbol: 'ADA', address: 'addr1...', network: 'Cardano' },
      { name: 'Ripple (XRP)', symbol: 'XRP', address: 'rXRP...', network: 'Ripple' },
      { name: 'Polkadot (DOT)', symbol: 'DOT', address: '1DOT...', network: 'Polkadot' },
      { name: 'Dogecoin (DOGE)', symbol: 'DOGE', address: 'DOGE...', network: 'Dogecoin' },
      { name: 'Litecoin (LTC)', symbol: 'LTC', address: 'ltc1...', network: 'Litecoin' },
      { name: 'Polygon (MATIC)', symbol: 'MATIC', address: '0xMNOP...', network: 'Polygon (Matic)' },
      { name: 'Avalanche (AVAX)', symbol: 'AVAX', address: 'X-avax1...', network: 'Avalanche C-Chain' },
      { name: 'TRON (TRX)', symbol: 'TRX', address: 'TRX...', network: 'TRC20' },
      { name: 'Shiba Inu (SHIB)', symbol: 'SHIB', address: '0xQRST...', network: 'ERC20' },
      { name: 'Chainlink (LINK)', symbol: 'LINK', address: '0xUVWX...', network: 'ERC20' },
      { name: 'Monero (XMR)', symbol: 'XMR', address: '4XMR...', network: 'Monero' },
      { name: 'Ethereum Classic (ETC)', symbol: 'ETC', address: '0xETC...', network: 'Ethereum Classic' },
      { name: 'Stellar (XLM)', symbol: 'XLM', address: 'GABC...', network: 'Stellar' },
      { name: 'Bitcoin Cash (BCH)', symbol: 'BCH', address: 'qrbch...', network: 'Bitcoin Cash' },
      { name: 'Algorand (ALGO)', symbol: 'ALGO', address: 'ALGO...', network: 'Algorand' },
      { name: 'VeChain (VET)', symbol: 'VET', address: '0xVET...', network: 'VeChain' },
      { name: 'Cosmos (ATOM)', symbol: 'ATOM', address: 'cosmos1...', network: 'Cosmos' },
      { name: 'Filecoin (FIL)', symbol: 'FIL', address: 'f1fil...', network: 'Filecoin' },
      { name: 'Dai (DAI)', symbol: 'DAI', address: '0xDAI...', network: 'ERC20' },
    ];
  